import 'question.dart';

const questionCatalog = <Question>[
  Question(
    id: 'q_001',
    text: 'What is something small I do that makes you feel loved?',
    topic: QuestionTopic.connection,
    vibe: QuestionVibe.reflective,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_002',
    text: 'When did you last feel completely yourself around me?',
    topic: QuestionTopic.connection,
    vibe: QuestionVibe.reflective,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_003',
    text: 'Tell me about a moment together you keep coming back to.',
    topic: QuestionTopic.connection,
    vibe: QuestionVibe.deep,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.prompt,
  ),
  Question(
    id: 'q_004',
    text: 'Make me laugh with the silliest memory of us you can think of.',
    topic: QuestionTopic.connection,
    vibe: QuestionVibe.playful,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.challenge,
  ),
  Question(
    id: 'q_005',
    text: 'What is one thing you wish I asked you about more often?',
    topic: QuestionTopic.communication,
    vibe: QuestionVibe.reflective,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_006',
    text: 'When was the last time you felt truly heard by me?',
    topic: QuestionTopic.communication,
    vibe: QuestionVibe.deep,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_007',
    text: 'How can I make it easier for you to share hard things with me?',
    topic: QuestionTopic.communication,
    vibe: QuestionVibe.reflective,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_008',
    text: 'Share one thing you have been meaning to tell me but kept delaying.',
    topic: QuestionTopic.communication,
    vibe: QuestionVibe.deep,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.prompt,
  ),
  Question(
    id: 'q_009',
    text: 'If we could do anything together this weekend, what would it be?',
    topic: QuestionTopic.fun,
    vibe: QuestionVibe.playful,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_010',
    text: 'Invent a holiday just for us and explain how we would celebrate it.',
    topic: QuestionTopic.fun,
    vibe: QuestionVibe.playful,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.challenge,
  ),
  Question(
    id: 'q_011',
    text: 'Pick a song that captures our last month together.',
    topic: QuestionTopic.fun,
    vibe: QuestionVibe.playful,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.prompt,
  ),
  Question(
    id: 'q_012',
    text:
        'What is the most ridiculous thing you have ever wanted to do with me?',
    topic: QuestionTopic.fun,
    vibe: QuestionVibe.playful,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_013',
    text: 'Where do you imagine us being five years from now?',
    topic: QuestionTopic.future,
    vibe: QuestionVibe.reflective,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_014',
    text: 'What is a dream of yours you have not told me yet?',
    topic: QuestionTopic.future,
    vibe: QuestionVibe.deep,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_015',
    text: 'Describe the home you would love for us one day.',
    topic: QuestionTopic.future,
    vibe: QuestionVibe.reflective,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.prompt,
  ),
  Question(
    id: 'q_016',
    text: 'What value do you most want our relationship to be built on?',
    topic: QuestionTopic.coreValues,
    vibe: QuestionVibe.deep,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_017',
    text: 'Whose love do you most want ours to resemble, and why?',
    topic: QuestionTopic.coreValues,
    vibe: QuestionVibe.reflective,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_018',
    text: 'What does loyalty mean to you in everyday moments?',
    topic: QuestionTopic.coreValues,
    vibe: QuestionVibe.deep,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_019',
    text: 'What is one tiny daily ritual you would like us to keep forever?',
    topic: QuestionTopic.lifestyle,
    vibe: QuestionVibe.reflective,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_020',
    text: 'If we swapped routines for a day, what would surprise you most?',
    topic: QuestionTopic.lifestyle,
    vibe: QuestionVibe.playful,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_021',
    text: 'How do you like to recharge after a long week, and how can I help?',
    topic: QuestionTopic.lifestyle,
    vibe: QuestionVibe.reflective,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_022',
    text: 'What kind of touch makes you feel most safe with me?',
    topic: QuestionTopic.intimacy,
    vibe: QuestionVibe.reflective,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_023',
    text: 'When did you last feel really close to me, and what did I do?',
    topic: QuestionTopic.intimacy,
    vibe: QuestionVibe.deep,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.question,
  ),
  Question(
    id: 'q_024',
    text: 'Whisper one thing you wish I would do more often.',
    topic: QuestionTopic.intimacy,
    vibe: QuestionVibe.flirty,
    explicitness: QuestionExplicitness.suggestive,
    format: QuestionFormat.prompt,
  ),
  Question(
    id: 'q_025',
    text: 'Describe the kind of evening that would make me hard to forget.',
    topic: QuestionTopic.intimacy,
    vibe: QuestionVibe.flirty,
    explicitness: QuestionExplicitness.suggestive,
    format: QuestionFormat.prompt,
  ),
  Question(
    id: 'q_026',
    text: 'Compliment me in a way you have never tried before.',
    topic: QuestionTopic.fun,
    vibe: QuestionVibe.flirty,
    explicitness: QuestionExplicitness.none,
    format: QuestionFormat.challenge,
  ),
];
